name: Block .bak files

'on':
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  no-bak-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fail if *.bak files exist
        run: |
          set -euo pipefail
          if git ls-files "*.bak" | grep -q ".bak$"; then
            echo "Error: .bak snapshot files detected in the tree:" >&2
            git ls-files "*.bak" >&2
            exit 1
          fi
          echo "No .bak files found."
